databases:
  - name: ai_blog_app_db
    plan: free
    databaseName: ai_blog_app_db
    user: lizwi

services:
  - type: web
    plan: free
    name: ai_blog_app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn ai_blog_app.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai_blog_app_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
